---
id: AWCFNA
name: North America
areaConfigurations:
- areaCode: "ag"
  elections:
    national:
      dates:
        13: "2004-03-23"
        14: "2009-03-12"
        15: "2014-06-12"
        16: "2018-03-21"
        17: "2023-01-18"
        18: "≤2028-01"
  translations:
    de: "Antigua und Barbuda"
    en: "Antigua and Barbuda"
    eo: "Antigvo kaj Barbudo"
    fr: "Antigua-et-Barbuda"
    nl: "Antigua en Barbuda"
    no: "Antigua og Barbuda"
- areaCode: "ai"
  elections:
    national:
      dates:
        21: "2000-03-03"
        22: "2005-02-21"
        23: "2010-02-15"
        24: "2015-04-22"
        25: "2020-06-29"
        26: "2025-02-26"
        27: "≤2030-02"
  translations:
    de: "Anguilla"
    en: "Anguilla"
    eo: "Angvilo"
    fr: "Anguilla"
    nl: "Anguilla"
    no: "Anguilla"
- areaCode: "bm"
  elections:
    national:
      dates:
        16: "2003-07-24"
        17: "2007-12-18"
        18: "2012-12-17"
        19: "2017-07-18"
        20: "2020-10-01"
        21: "2025-02-18"
        22: "≤2030-02"
  translations:
    de: "Bermuda"
    en: "Bermuda"
    eo: "Bermudo"
    fr: "Bermudes"
    nl: "Bermuda"
    no: "Bermuda"
- areaCode: "ca"
  elections:
    national:
      dates:
        37: "2000-11-27"
        38: "2004-06-28"
        39: "2006-01-23"
        40: "2008-10-14"
        41: "2011-05-02"
        42: "2015-10-19"
        43: "2019-10-21"
        44: "2021-09-20"
        45: "2025-04-28"
        46: "≤2029-10-15"
  translations:
    de: "Kanada"
    en: "Canada"
    eo: "Kanado"
    fr: "Canada"
    nl: "Canada"
    no: "Canada"
- areaCode: "cr"
  csvConfiguration:
    electoralListIds:
    - "CR195101"
    - "CR200001"
    - "CR198301"
    - "CR200501"
    - "CR200401"
    - "CR201801"
    - "CR199601"
    - "CR201401"
    - "CR201201"
    - "CR202201"
    - "CR201802"
    - "CR202501"
    - "CR201601"
    - "CR202401"
  elections:
    national:
      dates:
        51: "2002-02-03"
        52: "2006-02-05"
        53: "2010-02-07"
        54: "2014-02-02"
        55: "2018-02-04"
        56: "2022-02-06"
        57: "2026-02-01"
    presidential:
      dates:
        47: "2002-02-03+2002-04-07"
        48: "2006-02-05"
        49: "2010-02-07"
        50: "2014-02-02+2014-04-06"
        51: "2018-02-04+2018-04-01"
        52: "2022-02-06+2022-04-03"
        53: "2026-02-01"
  translations:
    de: "Costa Rica"
    en: "Costa Rica"
    eo: "Kostariko"
    fr: "Costa Rica"
    nl: "Costa Rica"
    no: "Costa Rica"
- areaCode: "cw"
  elections:
    national:
      dates:
        1: "2010-08-27"
        2: "2012-10-19"
        3: "2016-10-05"
        4: "2017-04-28"
        5: "2021-03-19"
        6: "2025-03-21"
        7: "≤2029-03"
  translations:
    de: "Curaçao"
    en: "Curaçao"
    eo: "Kuracao"
    fr: "Curaçao"
    nl: "Curaçao"
    no: "Curaçao"
- areaCode: "gl"
  csvConfiguration:
    electoralListIds:
    - "GL197701"
    - "GL197801"
    - "GL200201"
    - "GL201401"
    - "GL197802"
    - "GL201701"
    - "GL201801"
  elections:
    national:
      dates:
        15: "2002-12-03"
        16: "2005-11-22"
        17: "2009-06-02"
        18: "2013-03-12"
        19: "2014-11-28"
        20: "2018-04-24"
        21: "2021-04-06"
        22: "2025-03-11"
        23: "≤2029-03"
  translations:
    de: "Grönland"
    en: "Greenland"
    eo: "Gronlando"
    fr: "Groenland"
    nl: "Groenland"
    no: "Grønland"
- areaCode: "gt"
  elections:
    national:
      dates:
        34: "2003-11-09"
        35: "2007-09-09"
        36: "2011-09-11"
        37: "2015-09-06"
        38: "2019-06-16"
        39: "2023-06-25"
        40: "≈2027-06"
    presidential:
      dates:
        25: "2003-11-09+2003-12-28"
        26: "2007-09-09+2007-11-04"
        27: "2011-09-11+2011-11-06"
        28: "2015-09-06+2015-10-25"
        29: "2019-06-16+2019-08-11"
        30: "2023-06-25+2023-08-20"
        31: "≈2027-06"
  translations:
    de: "Guatemala"
    en: "Guatemala"
    eo: "Gvatemalo"
    fr: "Guatemala"
    nl: "Guatemala"
    no: "Guatemala"
- areaCode: "hn"
  elections:
    national:
      dates:
        35: "2001-11-25"
        36: "2005-11-27"
        37: "2009-11-29"
        38: "2013-11-24"
        39: "2017-11-26"
        40: "2021-11-28"
        41: "2025-11-30"
        42: "≤2029-11"
    presidential:
      dates:
        32: "2001-11-25"
        33: "2005-11-27"
        34: "2009-11-29"
        35: "2013-11-24"
        36: "2017-11-26"
        37: "2021-11-28"
        38: "2025-11-30"
        39: "≈2029-11"
  translations:
    de: "Honduras"
    en: "Honduras"
    eo: "Honduro"
    fr: "Honduras"
    nl: "Honduras"
    no: "Honduras"
- areaCode: "ht"
  elections:
    national:
      dates:
        53: "2000-05-21+2000-07-09"
        54: "2006-02-07"
        55: "2010-11-28"
        56: "2015-08-09+2016-11-20"
        57: "2026-08-30"
    presidential:
      dates:
        7: "2000-11-26"
        8: "2006-02-07"
        9: "2010-11-10+2011-03-20"
        10: "2015-10-25"
        11: "2016-02-13+2016-02-14"
        12: "2016-11-20"
        13: "2026-08-30"
  translations:
    de: "Haiti"
    en: "Haiti"
    eo: "Haitio"
    fr: "Haïti"
    nl: "Haïti"
    no: "Haiti"
- areaCode: "jm"
  csvConfiguration:
    electoralListIds:
    - "JM194301"
    - "JM193801"
  elections:
    national:
      dates:
        26: "2002-10-16"
        27: "2007-09-03"
        28: "2011-12-29"
        29: "2016-02-25"
        30: "2020-09-03"
        31: "2025-09-03"
        32: "≤2030-09"
  translations:
    de: "Jamaika"
    en: "Jamaica"
    eo: "Jamajko"
    fr: "Jamaïque"
    nl: "Jamaica"
    no: "Jamaica"
- areaCode: "ky"
  elections:
    national:
      dates:
        20: "2000-11-08"
        21: "2005-05-11"
        22: "2009-05-20"
        23: "2013-05-22"
        24: "2017-05-24"
        25: "2021-04-14"
        26: "2025-04-30"
        27: "≤2029-04"
  translations:
    de: "Kaimaninseln"
    en: "Cayman Islands"
    eo: "Kajmana Insularo"
    fr: "Îles Caïmans"
    nl: "Kaaimaneilanden"
    no: "Caymanøyene"
- areaCode: "lc"
  elections:
    national:
      dates:
        17: "2001-12-03"
        18: "2006-12-11"
        19: "2011-11-28"
        20: "2016-06-06"
        21: "2021-07-26"
        22: "2025-12-01"
        23: "≤2030-12"
  translations:
    de: "Saint Lucia"
    en: "Saint Lucia"
    eo: "Sankta Lucio"
    fr: "Sainte-Lucie"
    nl: "Saint Lucia"
    no: "Saint Lucia"
- areaCode: "sv"
  csvConfiguration:
    electoralListIds:
    - "SV201701"
    - "SV198101"
    - "SV201001"
    - "SV198001"
    - "SV196101"
    - "SV200501"
    - "SV196001"
    - "SV201702"
    - "SV201901"
    - "SV202201"
    - "SV202101"
    - "SV198501"
    - "SV201301"
  elections:
    national:
      dates:
        28: "2000-03-12"
        29: "2003-03-16"
        30: "2006-03-12"
        31: "2009-01-18"
        32: "2012-03-11"
        33: "2015-03-01"
        34: "2018-03-04"
        35: "2021-02-28"
        36: "2024-02-04"
        37: "≤2027-02"
    presidential:
      dates:
        42: "2004-03-21"
        43: "2009-03-15"
        44: "2014-02-02+2013-03-03"
        45: "2019-02-03"
        46: "2024-02-04"
        47: "≈2029-02"
  translations:
    de: "El Salvador"
    en: "El Salvador"
    eo: "Salvadoro"
    fr: "Salvador"
    nl: "El Salvador"
    no: "El Salvador"
- areaCode: "sx"
  elections:
    national:
      dates:
        14: "2003-05-23"
        15: "2007-04-20"
        16: "2010-09-17"
        17: "2014-08-29"
        18: "2016-09-26"
        19: "2018-02-26"
        20: "2020-01-09"
        21: "2024-01-11"
        22: "2024-08-19"
        23: "≤2028-08"
  translations:
    de: "Sint Maarten"
    en: "Sint Maarten"
    eo: "Sint-Maarten"
    fr: "Saint-Martin"
    nl: "Sint Maarten"
    no: "Sint Maarten"
- areaCode: "tc"
  elections:
    national:
      dates:
        22: "2003-04-24"
        23: "2007-02-09"
        24: "2012-11-09"
        25: "2016-12-15"
        26: "2021-02-19"
        27: "2025-02-07"
        28: "≤2030-02"
  translations:
    de: "Turks- und Caicosinseln"
    en: "Turks and Caicos Islands"
    eo: "Turkoj kaj Kajkoj"
    fr: "Îles Turques-et-Caïques"
    nl: "Turks- en Caicoseilanden"
    no: "Turks- og Caicosøyene"
- areaCode: "tt"
  elections:
    national:
      dates:
        16: "2000-12-11"
        17: "2001-12-10"
        18: "2002-10-07"
        19: "2007-11-05"
        20: "2010-05-24"
        21: "2015-09-07"
        22: "2020-08-10"
        23: "2025-04-28"
        24: "≤2030-04"
  translations:
    de: "Trinidad und Tobago"
    en: "Trinidad and Tobago"
    eo: "Trinidado kaj Tobago"
    fr: "Trinité-et-Tobago"
    nl: "Trinidad en Tobago"
    no: "Trinidad og Tobago"
- areaCode: "vc"
  elections:
    national:
      dates:
        14: "2001-03-28"
        15: "2005-12-07"
        16: "2010-12-13"
        17: "2015-12-09"
        18: "2020-11-05"
        19: "2025-11-27"
        20: "≤2030-11"
  translations:
    de: "St. Vincent und die Grenadinen"
    en: "Saint Vincent and the Grenadines"
    eo: "Sankta Vincento kaj la Grenadinoj"
    fr: "Saint-Vincent-et-les-Grenadines"
    nl: "Saint Vincent en de Grenadines"
    no: "Saint Vincent og Grenadinene"
widgetsConfiguration:
  tableFontFamily: "Alegreya Sans,'Helvetica Neue',Helvetica,sans-serif"
  tableStylesheets:
  - https://fonts.googleapis.com/css?family=Alegreya+Sans%3A400%2C700%2C400italic%2C700italic%2C600%2C600italic%7CAlegreya+Sans%3A400%2C500%2C600%2C700%2C400italic%2C700italic&ver=1
  - https://europeelects.eu/wp-content/themes/chaplin/style.css?ver=2.6.7
